config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users,
             :path => '',
             :path_names => {:sign_in => 'login', :singn_out => 'logout', :edit => 'profile'},
             :controllers => {:registrations => 'registrations'}
  


  resources  :users, only: [:show]
  resources  :rooms
  resources  :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :room

  # has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :photos

  geocoded_by :street_address
  after_validation :geocode, if: :street_address_changed?

    validates :room_type, presence: true
    validates :accommodate, presence: true
    validates :num_bedroom, presence: true
    validates :num_bed, presence: true
    validates :bldg_number, presence: true
    validates :num_bathroom, presence: true
    validates :list_name, presence: true,uniqueness: true, length: {maximum: 30}
    validates :summary, presence: true, length: {maximum: 100}
    validates :country, presence: true
    validates :city, presence: true
    validates :street_address, presence: true
    validates :nightly_price, presence: true
    validates :weekly_price, presence: true
    validates :monthly_price, presence: true
    validates :service_fee, presence: true
    validates :cleaing_fee, presence: true
    validates :security_deposit, presence: true
    validates :basic_fund, presence: true
    validates :property_type, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         :confirmable
  validates :fullname, presence: true, length: {maximum: 20}      
  validates :fname, presence: true, length: {maximum: 20}
  validates :lname, presence: true, length: {maximum: 20}

  has_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_paramters, if: :devise_controller?

  protected 
  def configure_permitted_paramters
  		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:fname,:lname,:email,:password, :fullname) }
  		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:fname,:lname,:email,:current_password,:phone_number, :description) }

   end

end
#,:Bdate
#,:Bdate

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def destroy
		@photo = Photo.find(params[:id])
		room = @photo.room

		@photo.destroy
		@photos = Photo.where(room_id: room.id)

		respond_to :js
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 protected 
   def update_resource(resource, params)
   	resource.update_without_password(params)
   end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def show
    @photos = @room.photos
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save

      if params[:images] 
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end

      @photos = @room.photos
      redirect_to edit_room_path(@room), notice: "Saved Successfully "
    else
      render :new
    end
  end

  def edit
    if current_user.id == @room.user.id
      @photos = @room.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  def update
    if @room.update(room_params)

      if params[:images] 
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end

      redirect_to edit_room_path(@room), notice: "The Room has been Updated"
    else
      render :edit
    end
  end

  private
    def set_room
      @room = Room.find(params[:id]) 
    end

    def room_params
      params.require(:room).permit(:room_type, :accommodate, :num_bedroom, :num_bed, :bldg_number, :num_bathroom, :list_name, :summary, :country, :city, :street_address,:nightly_price, :weekly_price, :monthly_price, :service_fee, :cleaing_fee, :security_deposit, :basic_fund, :is_restaurant, :is_store, :is_mall, :is_school, :is_gym, :is_park, :is_gas_station, :is_daycare, :is_collage, :is_hypermarket, :is_transportation, :is_hospital, :is_health_center, :is_indoor_fireplace, :is_doorman, :is_breakfast, :is_coffeeshop, :is_dryer, :is_washer, :is_family_friens, :is_home_gym, :is_hot_tub, :is_hangers, :is_hair_dryer, :is_iron, :is_essentials, :is_suitable_for_events, :is_internet, :is_tv, :is_hour_check_in, :is_pool, :is_pets_allowed, :is_wheelchair_accessible, :is_shampoo, :is_heating, :is_smoking_allowed, :is_air_conditioning, :is_elevator, :is_fan, :property_type, :is_kitchen, :home_rules, :cancellation,:images)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def avatar_url(user)
        gravatar_id = Digest::MD5::hexdigest(user.email).downcase
        "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?=identical&s=233"
    end

  #  def bootstrap_class_for flash_type
  #   case flash_type
  #     when :success
  #       "alert-success"
  #     when :error
  #       "alert-error"
  #     when :alert
  #       "alert-block"
  #     when :notice
  #       "alert-info"
  #     else
  #       flash_type.to_s
  #   end
  # end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirshipsPro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
    <body>
        <%= render 'shared/navbar'%>
         <%= render  "shared/message" %> 
      <%= yield %>
      </div>

    </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/carousel'%>
<%= render 'shared/options'%>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/_list.html.erb
<% if @photos %>

    <div class="row">
        <% @photos.each do |photo| %>       
            <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-heading preview">
                    <%= image_tag photo.image.url() %>
                  </div>
                  <div class="panel-body">
                    <span class="pull-right">
                        <i class="fa fa-times fa-lg"></i>
                    </span>
                  </div>
                </div>
            </div>
        <% end %>           
    </div>

<% end %>

app/views/photos/distroy.js.erb
$('#photos').html("<% j render 'photos/list '%>")

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="container room-view">
<div calss="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Your Listing", rooms_path, class: "sidebar-link sidebar-lebal active"%></li>
            <li class="sidebar-item"><%= link_to "Your Reservations", rooms_path, class: "sidebar-link sidebar-lebal"%></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
        <div class="panel-heading">
            Listing
        </div>
        <div class="panel-body">
          <% @rooms.each do |room|%>
            <div class="row">
              <div class="col-md-2">
                
              </div>
              <div class="col-md-7">
                  <h4><%= room.list_name %></h4>
              </div>
              <div class="col-md-3 right"><%= link_to "Update", edit_room_path(room), class: "btn btn-primary"%></div>
            </div>
          <% end %>
        </div> 
        </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="container room-description-view">
    <div class="panel-defualt">
     <div class="panel-body ">
        <!-- image -->
        <div class="row">
            <div class="col-md-12">
                
            </div>
        </div>

        <br/>

        <!-- Main Info -->
        <div class="row">
         <div class="col-md-8">
            <div class="row">
                <div class="col-md-3 tex-t-center">
                    <%= image_tag avatar_url(@room.user), class: "img-thumbnail avatar-large" %><br/>
                    <h3><% @room.user.fname%>Nour</h3>
                </div>
                <div class="col-md-9">
                    <h4><%= @room.list_name %></h4>
                    <%= @room.street_address %>
                    <%= @room.bldg_number%>
                <div class="row text-center row-space-1">
                    <div class="col-sm-3">
                     <i class="fa fa-home fa-2x"></i>
                    </div>
                    <div class="col-sm-3">
                     <i class="fa fa-users fa-2x"></i>
                    </div>
                    <div class="col-sm-3">
                     <i class="fa fa-bed fa-2x"></i>
                    </div>
                     <div class="col-sm-3">
                     <i class="material-icons" style="font-size: 34px">wc</i>
                    </div>

                    <div class="row text-center">
                        <div class="col-sm-3">
                            <%= @room.property_type %>
                        </div>
                        <div class="col-sm-3">
                            <%= @room.accommodate %> <%= @room.accommodate > 1 ? "Guests" : "Guest" %>
                        </div>
                        <div class="col-sm-3">
                            <%= @room.num_bedroom %> <%= @room.num_bedroom > 1 ? "Bedrooms" : "Bedroom" %>
                        </div>
                        <div class="col-sm-3">
                            <%= @room.num_bathroom %> <%= @room.num_bathroom > 1 ? "Bathrooms" : "Bathroom" %>
                        </div>
        
                    </div>
                </div>
                </div>
            </div>
         </div>
        </div>

        <!-- About -->
        <div class="row">
            <div class="col-md-6">
                <h2>About This Listing</h2>
                <p><%= @room.summary%></p>
            </div>
        </div>
        <hr>
        <br/>
        <!-- The Space -->
        <div class="row">
         <div class="col-md-2">
             <p style="font-family: cursive;color: #fd802f;font-size: 20px;"> The Space </p>
         </div>
         <div class="col-md-10">
             <div class="row">
                 <div class="col-md-6">
                     <ol class="the-space">
                        <li>Room type: <span class="space-info"><%= @room.room_type%></span> </li>
                        <li>Property type: <span class="space-info"><%= @room.property_type%></span></li>
                        <li>Accommodate: <span class="space-info"> <%= @room.accommodate%></span></li>
                     </ol>
                 </div>
                 <div class="col-md-6">
                    <ol class="the-space">
                        <li>Number Bedroom:  <span class="space-info"><%= @room.num_bedroom%> </span></li>
                        <li>Number Bed: <span class="space-info"><%= @room.num_bed%> </span></li>
                        <li>Number Bathroom: <span class="space-info"> <%= @room.num_bathroom%></span></li>
                    </ol>
                 </div>
             </div>
         </div>
        </div>
        <hr>
        <br/>
         <!-- Amentities -->
         <div class="row">
             <div class="col-md-2">
                 <p style="font-family: cursive;color: #fd802f;font-size: 20px;"> Amentities </p>
             </div>
             <div class="col-md-10">
                 <div class="row">
                     <div class="col-md-6">
                         <ul class="amentities">
                         <li class="<%= 'text-line-through' if !@room.is_breakfast %>">Breakfast</li>
                         <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
                         <li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
                         <li class="<%= 'text-line-through' if !@room.is_dryer %>">Dryer</li>
                         <li class="<%= 'text-line-through' if !@room.is_iron %>">Iron</li>
                         <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
                         <li class="<%= 'text-line-through' if !@room.is_pool %>">Pool</li>
                         <li class="<%= 'text-line-through' if !@room.is_fan %>">Fan</li>
                         <li class="<%= 'text-line-through' if !@room.is_hair_dryer %>">Hair Dryer</li>
                         <li class="<%= 'text-line-through' if !@room.is_hangers %>">Hangers</li>
                         <li class="<%= 'text-line-through' if !@room.is_hot_tub %>">Hot tub</li>
                         <li class="<%= 'text-line-through' if !@room.is_washer%>"> Washer</li>
                         <li class="<%= 'text-line-through' if !@room.is_elevator %>">Elevator</li>
                         <li class="<%= 'text-line-through' if !@room.is_indoor_fireplace %>">Indoor fireplace</li>
                         </ul>
                     </div>
                     <div class="col-md-6">
                        <ul class="amentities">
                         <li class="<%= 'text-line-through' if !@room.is_family_friens %>">Family/Friends</li>
                         <li class="<%= 'text-line-through' if !@room.is_home_gym %>">Home Gym</li>
                         <li class="<%= 'text-line-through' if !@room.is_essentials %>">Essentials</li>
                         <li class="<%= 'text-line-through' if !@room.is_suitable_for_events %>">Suitable For Events</li>
                         <li class="<%= 'text-line-through' if !@room.is_pets_allowed %>">Pets allowed</li>
                         <li class="<%= 'text-line-through' if !@room.is_hour_check_in %>">24 Hour Check In</li>
                         <li class="<%= 'text-line-through' if !@room.is_wheelchair_accessible %>">Wheelchair Accessible</li>
                         <li class="<%= 'text-line-through' if !@room.is_shampoo %>">Shampoo</li>
                         <li class="<%= 'text-line-through' if !@room.is_smoking_allowed %>">Smoking Allowed</li>
                         <li class="<%= 'text-line-through' if !@room.is_air_conditioning %>">Air Conditioning</li>
                         <li class="<%= 'text-line-through' if !@room.is_doorman %>">Doorman</li>
                        </ul>
                     </div>
                 </div>
             </div>
        </div>
        <hr>
        <br/>
        <!-- Near by -->
        <div class="row">
            <div class="col-md-2">
                <p style="font-family: cursive;color: #fd802f;font-size: 20px;"> Near by </p>
            </div>
            <div class="col-md-10">
                 <div class="row">
                     <div class="col-md-6">
                         <ul class="near-by">
                         <li class="<%= 'text-line-through' if !@room.is_restaurant %>">Rearurant</li>
                         <li class="<%= 'text-line-through' if !@room.is_store %>">Stores</li>
                         <li class="<%= 'text-line-through' if !@room.is_mall %>">Mall</li>
                         <li class="<%= 'text-line-through' if !@room.is_school %>">School</li>
                         <li class="<%= 'text-line-through' if !@room.is_gym %>">Gym</li>
                         <li class="<%= 'text-line-through' if !@room.is_park %>">Park</li>
                         <li class="<%= 'text-line-through' if !@room.is_gas_station %>">Gas station</li>

                         </ul>
                     </div>
                     <div class="col-md-6">
                        <ul class="near-by">
                         <li class="<%= 'text-line-through' if !@room.is_hypermarket %>">Hypermarket</li>
                         <li class="<%= 'text-line-through' if !@room.is_collage %>">Collage</li>
                         <li class="<%= 'text-line-through' if !@room.is_daycare %>">Daycare</li>
                         <li class="<%= 'text-line-through' if !@room.is_transportation%>">Transportation</li>
                         <li class="<%= 'text-line-through' if !@room.is_hospital %>">Hospital</li>
                         <li class="<%= 'text-line-through' if !@room.is_health_center %>">Health center</li>
                         <li class="<%= 'text-line-through' if !@room.is_coffeeshop %>">Coffeeshop</li>
                        </ul>
                     </div>
                 </div>
             </div>
        </div>
        <hr>
        <br/>
        <!-- Prices -->
        <div class="row">
         <div class="col-md-2">
             <p style="font-family: cursive;color: #fd802f;font-size: 20px;"> Prices </p>
         </div>
         <div class="col-md-10">
             <div class="row">
                 <div class="col-md-6">
                     <ol class="the-space">
                       <li>Nightly Price: <span class="space-info">$<%= @room.nightly_price%></span> </li>
                       <li>Weekly Price: <span class="space-info">$<%= @room.weekly_price%></span></li>
                       <li>Monthly Price: <span class="space-info">$<%= @room.monthly_price%></span></li>
                       <li>Basic Fund: <span class="space-info">$<%= @room.basic_fund%> </span></li>
                     </ol>
                 </div>
                 <div class="col-md-6">
                    <ol class="the-space">
                      <li>Service Fee:  <span class="space-info">$<%= @room.service_fee%> </span></li>
                      <li>Cleaning Fee: <span class="space-info">$<%= @room.cleaing_fee%> </span></li>
                      <li>Security Deposit: <span class="space-info">$<%= @room.security_deposit%></span></li>
                      <li>Cancellation: <span class="space-info"><%= @room.cancellation%> </span></li>
                    </ol>
                 </div>
             </div>
         </div>
        </div>
        <hr>
        <br/>

        <!-- Description -->
        <div class="row">
            <div class="col-md-2">
                <p style="font-family: cursive;color: #fd802f;font-size: 20px;">House Rules</p>
            </div>
            <div class="col-md-10">
                <div class="row">
                  <div class="col-md-6">
                    <p><%= @room.home_rules%></p>
                  </div> 
                </div>
            </div>
        </div>
        <hr>
        <br/>

        <!-- Map -->
        <div class="row">
            <div class="col-md-12">
             <div id="map"></div>
                <style>
                #map {
                    width: 100%;
                    height: 400px;
                }
                </style>
                <script>
                  function initMap() {
                    var mapDiv = document.getElementById('map');
                    var map = new google.maps.Map(mapDiv, {
                      center: {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>},
                      zoom: 14
                    });
                    var marker = new google.maps.Marker({
                    map: map,
                    position: {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>},
                    title: 'AirShips'
                    });
                    marker.setMap(map);
                  }
                </script>
                <script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
                    async defer>
                </script>

            </div>
        </div>

     </div>
    </div>
</div>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>

app/views/shared/_carousel.html.erb
 <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
    <ol class="carousel-indicators hidden-xs">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <%= image_tag("Italy1.jpg", :alt => "rss feed") %>
        </div>
        <div class="item">
            <%= image_tag("Italy2.jpg", :alt => "rss feed") %>
        </div>    
        <div class="item">
            <%= image_tag("Italy3.jpg", :alt => "rss feed") %>
        </div>
    </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="icon-next"></span>
    </a>
 </div>
</div>

app/views/shared/_devisemsg.html.erb
<% unless resource.errors.empty? %>
 <script type="text/javascript">
 	<% resource.errors.full_messages.each do |msg| %>
 		roastr.error('<%= msg %>')
 	<% end %>	
 </script>
<% end %>	

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
   <% flash.each do |f| %>
	 <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
	 	toastr['<%= type %>']('<%= f[1] %>')
   <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
 <!-- Static navbar -->
<div id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
 <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container navbar-container">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
              <i class="fa fa-bars"></i>
          </button>
          <a class="navbar-brand page-scroll" href="#page-top">
              <i class="fa fa-play-circle"></i><span class="light logo">AirShips</span> 
          </a>
      </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

          <% if(!user_signed_in?) %>
            <li><%= link_to "Sign In", new_user_session_path%></li>
            <li><%= link_to "Sign Up", new_user_registration_path%></li>
              <% else %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= image_tag avatar_url(current_user), class: "img-rounded avatar-small"%>&nbsp;
          <%= current_user.fname %>
           <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><a href="#">Your Trip</a></li>
              <li><a href="#">Wish List</a></li>
              <li><a href="#"><%= link_to "Edit Profile", edit_user_registration_path%></a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Account Setting</a></li>
              <li><a href="#"><%= link_to "Log out", destroy_user_session_path, method: :delete %></a></li>
            </ul>
          </li>
        <% end %>

        <li>
          <a href="#"><i class="fa fa-envelope-o"></i> Message </a>
        </li> 
         <li>
          <a href="#"><i class="fa fa-home fa-lg"></i> Become a Host </a>
        </li> 
      </ul>
    </div><!--/.nav-collapse -->
   </div>
  </div><!--/.container-fluid -->
</nav>

app/views/shared/_options.html.erb
<div class="options-contant text-center">  
  <div class="container full-page">
    <div class="row">
        <div class="options-title">
          <h1 style="color: #f57421;font-size: 55px;font-family: cursive"><span>Options</span></h1>
        </div>
        <div class="col-md-4 clearfix">
          <a href="#" style="color: white">   <div class="circleBase type1 " > <div class="circle-in"><h2>Make </h2>
             <h2> Your </h2>
             <h2> List</h2>
             </div></div></a>
        </div>
        <div class="col-md-4 clearfix "> 
           <a href="#" style="color: white"> <div class="circleBase type1"><div class="circle-in"><h2>Find</h2>
            <h2> Your </h2>
            <h2> Place</h2>
            </div></div></a>
        </div>
        <div class="col-md-4 clearfix ">
            <a href="#" style="color: white">  <div class="circleBase type1"><div class="circle-in"><h2>Make </h2>
             <h2> Your </h2>
             <h2> Wish List</h2>
             </div></div></a>
         </div>
      </div>
    </div>  
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="user-info">
      <div class="center">
        <%= image_tag avatar_url(@user), class: "avatar-full" %>
      </div>
      <div class="panel panel-default panel-content">
        <div class="panel-heading">Verification </div> 
        <div class="panel-body">
          Email Address<br>
          Phone Number
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-9 description-area">
    <h2><%= @user.fname %> <%= @user.lname %></h2>
    <div class="description row-space-3">
      <%= @user.description %>
    </div>
  </div>
</div>